use crate::cfg::{self, GetNameVer};
use crate::cfg::{BlockLabel, CfgType, ImmVar, Instruction, IsImmediate};
use crate::deadcode::{get_dest, get_sources};
use crate::ir::{Bop, UnOp};
use crate::parse::Primitive;
use crate::scan::{AddOp, EqOp, MulOp, RelOp};
use crate::ssa_construct::{dominator_sets, dominator_tree, get_graph, SSAVarLabel};
use maplit::{hashmap, hashset};
use std::cmp::min;
use std::collections::{HashMap, HashSet};
